### ISSUE TITLE
Server creation and hosting

### ISSUE THREAD

**Issue by NtlatlengL** [group6tuks/ClientAccountSystem#5]
Finding suitable server platform, and set up for open access

**Comment by u14402425** [comment]
Server created and hosted on Azure
URL: https://clientaccountssystem.azurewebsites.net
GitHub: https://github.com/azure-appservice-samples/NodeJS-EmptySiteTemplate
publishMethod="FTP" 
publishUrl="ftp://waws-prod-dm1-137.ftp.azurewebsites.windows.net/site/wwwroot" 
userName="ClientAccountsSystem\$ClientAccountsSystem" userPWD="qohXiQYiTHufEyc3lnDCoSGMPyPFltrjyChADRno6Kqo7sXit3fvrJD3uKFj"
